version: '3.8'

services:
  proxy:
    image: 'nginx:stable-alpine'
    container_name: student_dashboard_proxy
    ports:
      - '8081:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back:/var/www/laravel
    depends_on:
      - back
    networks:
      - app_network
  
  back:
    image: php:8.1-fpm
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: student_dashboard_back
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: student_dashboard
      DB_USERNAME: root
      DB_PASSWORD: root
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    working_dir: /var/www/laravel
    volumes:
      - ./back:/var/www/laravel
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  # frontend:
  #   image: node:18
  #   container_name: student_dashboard_front
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   command: ["npm", "start"]
  #   networks:
  #     - app_network

networks:
  app_network:

volumes:
  postgres_data:
